# Generated by Django 5.2.8 on 2025-11-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
