# Generated by Django 5.2.8 on 2025-11-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_user_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
    ]
