# Generated by Django 5.2.8 on 2025-12-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="balance",
        ),
    ]
